/**********************************************************************************/
/* Wmoge game engine                                                              */
/* Available at github https://github.com/EgorOrachyov/wmoge                      */
/**********************************************************************************/
/* MIT License                                                                    */
/*                                                                                */
/* Copyright (c) 2023 Egor Orachyov                                               */
/*                                                                                */
/* Permission is hereby granted, free of charge, to any person obtaining a copy   */
/* of this software and associated documentation files (the "Software"), to deal  */
/* in the Software without restriction, including without limitation the rights   */
/* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell      */
/* copies of the Software, and to permit persons to whom the Software is          */
/* furnished to do so, subject to the following conditions:                       */
/*                                                                                */
/* The above copyright notice and this permission notice shall be included in all */
/* copies or substantial portions of the Software.                                */
/*                                                                                */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR     */
/* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,       */
/* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE    */
/* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER         */
/* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,  */
/* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  */
/* SOFTWARE.                                                                      */
/**********************************************************************************/

#pragma once

#include "core/array_view.hpp"
#include "gfx/gfx_buffers.hpp"
#include "gfx/gfx_vector.hpp"
#include "mesh/mesh_bucket.hpp"
#include "mesh/mesh_pass.hpp"
#include "render/render_defs.hpp"

#include "../../shaders/tmp/generated/auto_material_reflection.hpp"

namespace wmoge {

    /**
     * @brief (Autogenerated) Per-frame global allocated data passed to GPU for rendering
     * @note Matrices in column-major format as on gpu
     */
    using GPUFrameData = ShaderMaterial::FrameData;

    /**
     * @brief (Autogenerated) Common view data and matrices passed to GPU for rendering
     * @note Matrices in column-major format as on gpu
     */
    using GPUViewData = ShaderMaterial::ViewData;

    /**
     * @brief (Autogenerated) Single render object data passed to a GPU for rendering
     * @note Matrices in column-major format as on gpu
     */
    using GPURenderObjectData = ShaderMaterial::RenderObjectData;

    /** @brief Gpu vector to store render object persistent gpu data */
    using GPURenderObjectDataVector = GfxVector<GPURenderObjectData, GfxStorageBuffer>;

    /** @brief Gpu vector for per-frame id placement for instancing and data fetch on gpu */
    using GPURenderObjectIdVector = GfxVector<int, GfxVertBuffer>;

    /**
     * @class RenderScene
     * @brief Render Engine side scene representation with cached GPU data
     */
    class RenderScene {
    public:
        RenderScene();

        // void flush_buffers(class GfxCmdList* gfx_ctx);

        [[nodiscard]] MeshBucketMap&             get_bucket_map(MeshPassType pass_type) { return m_bucket_map[int(pass_type)]; }
        [[nodiscard]] GPURenderObjectDataVector& get_objects_gpu_data() { return m_objects_gpu_data; }
        [[nodiscard]] GPURenderObjectIdVector&   get_objects_ids() { return m_objects_ids; }

    private:
        MeshBucketMap             m_bucket_map[MESH_PASSES_TOTAL];//< Bucket slot map per pass type for dynamic instancing
        GPURenderObjectIdVector   m_objects_ids;                  //< Remap ids to render data
        GPURenderObjectDataVector m_objects_gpu_data;             //< Scene render objects gpu data (to fetch in shader by id)
        std::vector<int>          m_free_objects_ids;             //< Pool with free ids
    };

}// namespace wmoge