/**********************************************************************************/
/* Wmoge game engine                                                              */
/* Available at github https://github.com/EgorOrachyov/wmoge                      */
/**********************************************************************************/
/* MIT License                                                                    */
/*                                                                                */
/* Copyright (c) 2023 Egor Orachyov                                               */
/*                                                                                */
/* Permission is hereby granted, free of charge, to any person obtaining a copy   */
/* of this software and associated documentation files (the "Software"), to deal  */
/* in the Software without restriction, including without limitation the rights   */
/* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell      */
/* copies of the Software, and to permit persons to whom the Software is          */
/* furnished to do so, subject to the following conditions:                       */
/*                                                                                */
/* The above copyright notice and this permission notice shall be included in all */
/* copies or substantial portions of the Software.                                */
/*                                                                                */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR     */
/* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,       */
/* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE    */
/* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER         */
/* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,  */
/* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  */
/* SOFTWARE.                                                                      */
/**********************************************************************************/

#ifndef WMOGE_RENDER_SCENE_HPP
#define WMOGE_RENDER_SCENE_HPP

#include "gfx/gfx_buffers.hpp"
#include "gfx/gfx_vector.hpp"

#include "shaders/generated/auto_material_reflection.hpp"

namespace wmoge {

    /**
     * @brief (Autogenerated) Per-frame global allocated data passed to GPU for rendering
     */
    using GPUFrameData = ShaderMaterial::FrameData;

    /**
     * @brief (Autogenerated) Common view data and matrices passed to GPU for rendering
     */
    using GPUViewData = ShaderMaterial::ViewData;

    /**
     * @brief (Autogenerated) Single render object data passed to a GPU for rendering
     */
    using GPURenderObjectData = ShaderMaterial::RenderObjectData;

    /**
     * @class RenderScene
     * @brief Render Engine side scene representation with cached GPU data
     */
    class RenderScene {
    public:
        RenderScene();

        void flush_buffers(class GfxCtx* gfx_ctx);

        [[nodiscard]] GfxVector<GPURenderObjectData, GfxStorageBuffer>& get_render_objects_data() { return m_render_objects_data; }
        [[nodiscard]] GfxVector<int, GfxVertBuffer>&                    get_objects_ids() { return m_objects_ids; }

    private:
        GfxVector<GPURenderObjectData, GfxStorageBuffer> m_render_objects_data;//< Scene render objects data
        GfxVector<int, GfxVertBuffer>                    m_objects_ids;        //< Remap ids to render data
    };

}// namespace wmoge

#endif//WMOGE_RENDER_SCENE_HPP
